In [8]:
import pandas as pd

f = "20221004Realtorcom_Scraped_Listings.csv"

In [9]:
# read data into df
df = pd.read_csv(f)
df = df.drop(columns=["Unnamed: 0"])
df

,solddate,price,beds,baths,sqft,sqftlot,href
0,"Sold - Sep 13, 2022","$650,000",3bed,2.5bath,"2,122sqft",1.38acre lot,/realestateandhomes-detail/4-Pheasant-Pl_Carme...
1,"Sold - Sep 13, 2022","$675,000",4bed,3bath,"2,769sqft",1.43acre lot,/realestateandhomes-detail/317-W-Shore-Dr_Carm...
2,"Sold - Sep 8, 2022","$630,000",3bed,2.5bath,"2,531sqft",1.04acre lot,/realestateandhomes-detail/80-Drovers-Ln_Brews...
3,"Sold - Sep 8, 2022","$645,000",3bed,2.5bath,"2,688sqft",1.21acre lot,/realestateandhomes-detail/56-Glenvue-Dr_Carme...
4,"Sold - Sep 8, 2022","$549,000",3bed,2.5bath,"2,032sqft",2.93acre lot,/realestateandhomes-detail/64-Queens-Way_Mahop...
...,...,...,...,...,...,...,...
247,"Sold - Apr 27, 2022","$750,000",3bed,2.5bath,"2,360sqft",1.05acre lot,/realestateandhomes-detail/40-Dads-Ln_Stamford...
248,"Sold - Apr 26, 2022","$710,000",4bed,4bath,"3,010sqft",1acre lot,/realestateandhomes-detail/48-Country-Ridge-Dr...
249,"Sold - Apr 26, 2022","$737,000",4bed,2.5bath,"2,469sqft",1.06acre lot,/realestateandhomes-detail/22-McIntosh-Ct_Stam...
250,"Sold - Apr 26, 2022","$725,000",4bed,3.5bath,"3,039sqft",1.59acre lot,/realestateandhomes-detail/48-Cherry-Hill-Rd_C...
251,"Sold - Apr 25, 2022","$463,000",2bed,1bath,"1,728sqft",1.15acre lot,/realestateandhomes-detail/420-Sprout-Brook-Rd...

In [10]:
# basic formatting so data easy to filter
df["beds"] = df["beds"].str[:-3]
df["beds"] = df["beds"].str.replace(',', '').astype(int)
df["baths"] = df["baths"].str[:-4]
df["sqft"] = df["sqft"].str[:-4]
df["sqft"] = df["sqft"].str.replace(',', '').astype(int)
df["sqftlot"] = df["sqftlot"].str[:-8]
df["sqftlot"] = df["sqftlot"].str.replace(',', '').astype(float)
df["solddate"] = df["solddate"].str[7:]
df['solddate']= pd.to_datetime(df['solddate'])
df["price"] = df["price"].str[1:]
df["price"] = df["price"].str.replace(',', '').astype(float)
df

,solddate,price,beds,baths,sqft,sqftlot,href
0,2022-09-13,650000.0,3,2.5,2122,1.38,/realestateandhomes-detail/4-Pheasant-Pl_Carme...
1,2022-09-13,675000.0,4,3,2769,1.43,/realestateandhomes-detail/317-W-Shore-Dr_Carm...
2,2022-09-08,630000.0,3,2.5,2531,1.04,/realestateandhomes-detail/80-Drovers-Ln_Brews...
3,2022-09-08,645000.0,3,2.5,2688,1.21,/realestateandhomes-detail/56-Glenvue-Dr_Carme...
4,2022-09-08,549000.0,3,2.5,2032,2.93,/realestateandhomes-detail/64-Queens-Way_Mahop...
...,...,...,...,...,...,...,...
247,2022-04-27,750000.0,3,2.5,2360,1.05,/realestateandhomes-detail/40-Dads-Ln_Stamford...
248,2022-04-26,710000.0,4,4,3010,1.00,/realestateandhomes-detail/48-Country-Ridge-Dr...
249,2022-04-26,737000.0,4,2.5,2469,1.06,/realestateandhomes-detail/22-McIntosh-Ct_Stam...
250,2022-04-26,725000.0,4,3.5,3039,1.59,/realestateandhomes-detail/48-Cherry-Hill-Rd_C...
251,2022-04-25,463000.0,2,1,1728,1.15,/realestateandhomes-detail/420-Sprout-Brook-Rd...

In [11]:
# break out address elements
df["address"] = df["href"].str[27:]
df['street'] = df['address'].str.split(pat='_', expand=True).get(0)
df['town'] = df['address'].str.split(pat='_', expand=True).get(1)
df['state'] = df['address'].str.split(pat='_', expand=True).get(2)
df['zip'] = df['address'].str.split(pat='_', expand=True).get(3)
df['month'] = df['solddate'].dt.strftime('%Y-%m')
df

,solddate,price,beds,baths,sqft,sqftlot,href,address,street,town,state,zip,month
0,2022-09-13,650000.0,3,2.5,2122,1.38,/realestateandhomes-detail/4-Pheasant-Pl_Carme...,4-Pheasant-Pl_Carmel_NY_10512_M40915-44958,4-Pheasant-Pl,Carmel,NY,10512,2022-09
1,2022-09-13,675000.0,4,3,2769,1.43,/realestateandhomes-detail/317-W-Shore-Dr_Carm...,317-W-Shore-Dr_Carmel_NY_10512_M30537-88885,317-W-Shore-Dr,Carmel,NY,10512,2022-09
2,2022-09-08,630000.0,3,2.5,2531,1.04,/realestateandhomes-detail/80-Drovers-Ln_Brews...,80-Drovers-Ln_Brewster_NY_10509_M30283-65288,80-Drovers-Ln,Brewster,NY,10509,2022-09
3,2022-09-08,645000.0,3,2.5,2688,1.21,/realestateandhomes-detail/56-Glenvue-Dr_Carme...,56-Glenvue-Dr_Carmel_NY_10512_M36797-19027,56-Glenvue-Dr,Carmel,NY,10512,2022-09
4,2022-09-08,549000.0,3,2.5,2032,2.93,/realestateandhomes-detail/64-Queens-Way_Mahop...,64-Queens-Way_Mahopac_NY_10541_M40892-60363,64-Queens-Way,Mahopac,NY,10541,2022-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2022-04-27,750000.0,3,2.5,2360,1.05,/realestateandhomes-detail/40-Dads-Ln_Stamford...,40-Dads-Ln_Stamford_CT_06903_M39811-27866,40-Dads-Ln,Stamford,CT,06903,2022-04
248,2022-04-26,710000.0,4,4,3010,1.00,/realestateandhomes-detail/48-Country-Ridge-Dr...,48-Country-Ridge-Dr_Monroe_CT_06468_M47769-42251,48-Country-Ridge-Dr,Monroe,CT,06468,2022-04
249,2022-04-26,737000.0,4,2.5,2469,1.06,/realestateandhomes-detail/22-McIntosh-Ct_Stam...,22-McIntosh-Ct_Stamford_CT_06903_M32613-10293,22-McIntosh-Ct,Stamford,CT,06903,2022-04
250,2022-04-26,725000.0,4,3.5,3039,1.59,/realestateandhomes-detail/48-Cherry-Hill-Rd_C...,48-Cherry-Hill-Rd_Carmel_NY_10512_M43259-73630,48-Cherry-Hill-Rd,Carmel,NY,10512,2022-04
251,2022-04-25,463000.0,2,1,1728,1.15,/realestateandhomes-detail/420-Sprout-Brook-Rd...,420-Sprout-Brook-Rd_Garrison_NY_10524_M46978-0...,420-Sprout-Brook-Rd,Garrison,NY,10524,2022-04

In [12]:
# criteria for analysis
df2 = df.loc[df['sqftlot'] > 1.99]
df2 = df2.loc[df['sqft'] > 1200]
df2 = df2.loc[df['beds'] < 5]

In [13]:
# create pivot by state
table = pd.pivot_table(df2, values='price', index=['month'],columns=['state'], aggfunc='mean')
table

state               CT             NY
month
2022-04  800000.000000            NaN
2022-05  670222.222222  770000.000000
2022-06  583461.538462  545833.333333
2022-07  649641.176471  551666.666667
2022-08  692888.888889  598166.666667
2022-09  626750.000000  599500.000000

In [14]:
# get count of sales per month
table = pd.pivot_table(df2, values='price', index=['month'],columns=['state'], aggfunc='count')
table

state      CT   NY
month
2022-04   1.0  NaN
2022-05   9.0  2.0
2022-06  13.0  3.0
2022-07  17.0  3.0
2022-08  18.0  6.0
2022-09   4.0  2.0